### ISSUE TITLE
Loading level into with hammer object (and width/height set) level editor crashes TBE

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#117]
If you load a level into the editor with a hammer object present, and this object has height and/or width set, TBE crashes.

Backtrace of `gdb`:

```
#0  0x00000000004a3e06 in QListData::end (this=0x98) at /usr/include/qt/QtCore/qlist.h:109
#1  0x00000000004eeae0 in QList<std::shared_ptr<AbstractObject> >::contains_impl (this=0x98, t=std::shared_ptr (count 2, weak 1) 0xc1d190)
    at /usr/include/qt/QtCore/qlist.h:978
#2  0x00000000004edd7c in QList<std::shared_ptr<AbstractObject> >::contains (this=0x98, t=std::shared_ptr (count 2, weak 1) 0xc1d190) at /usr/include/qt/QtCore/qlist.h:972
#3  0x00000000004eb207 in World::addObject (this=0x0, anObjectPtr=std::shared_ptr (count 2, weak 1) 0xc1d190) at /home/wuzzy/src/tbe/tbe/src/model/World.cpp:109
#4  0x00000000004c3be5 in AbstractObject::parseProperties (this=0xc78b80) at /home/wuzzy/src/tbe/tbe/src/model/AbstractObject.cpp:262
#5  0x00000000004e07f1 in RectObject::parseProperties (this=0xc78b80) at /home/wuzzy/src/tbe/tbe/src/model/RectObject.cpp:193
#6  0x00000000004c41c5 in AbstractObject::setTheWidth (this=0xc78b80, new_var=0.45000000000000001, mustRunParseProperties=true)
    at /home/wuzzy/src/tbe/tbe/src/model/AbstractObject.cpp:312
#7  0x00000000004abf10 in AbstractObjectSerializer::createObjectFromDom (q=..., isMovable=false, isXYMandatory=true)
    at /home/wuzzy/src/tbe/tbe/src/loadsave/AbstractObjectSerializer.cpp:155
#8  0x00000000004b4934 in Level::load (this=0xbfaac0, aFileName=..., aLevelInfoToolbox=0xb90d30) at /home/wuzzy/src/tbe/tbe/src/loadsave/Level.cpp:283
#9  0x0000000000511594 in MainWindow::loadLevel (this=0x7fffffffe090, aFileName=...) at /home/wuzzy/src/tbe/tbe/src/view/MainWindow.cpp:90
#10 0x000000000051229f in MainWindow::on_action_Open_File_triggered (this=0x7fffffffe090) at /home/wuzzy/src/tbe/tbe/src/view/MainWindow.cpp:244
#11 0x00000000005346f1 in MainWindow::qt_static_metacall (_o=0x7fffffffe090, _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fffffffd220)
    at /home/wuzzy/src/tbe/tbe/build/src/moc_MainWindow.cpp:275
#12 0x0000000000534892 in MainWindow::qt_metacall (this=0x7fffffffe090, _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fffffffd220)
    at /home/wuzzy/src/tbe/tbe/build/src/moc_MainWindow.cpp:313
#13 0x00007ffff6fe34d0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff789dd92 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff78a0218 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff7a22b72 in ?? () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff7a28e2c in ?? () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff7a2cd70 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff78ea9c8 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff7a2d7b3 in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff78a79ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff78ad589 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff6fb4bab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#24 0x00007ffff78ac492 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff790529d in ?? () from /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff79074fb in ?? () from /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff78a79ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff78ace86 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff6fb4bab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#30 0x00007ffff72f55f1 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#31 0x00007ffff72f72b5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#32 0x00007ffff72dc6d8 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#33 0x00007fffedb308c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#34 0x00007ffff57aadc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#35 0x00007ffff57ab020 in ?? () from /usr/lib/libglib-2.0.so.0
#36 0x00007ffff57ab0cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#37 0x00007ffff700b54f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#38 0x00007ffff6fb257a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#39 0x00007ffff6fba53c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#40 0x00000000004c0f9c in main (argc=1, argv=0x7fffffffe418) at /home/wuzzy/src/tbe/tbe/src/main.cpp:285
```

Code of a level with just a hammer in it, for you to reproduce:
```
<!DOCTYPE mydocument>
<tbe-level>
    <levelinfo>
        <title></title>
        <author></author>
        <license></license>
        <description></description>
        <date>2/1/16</date>
    </levelinfo>
    <toolbox/>
    <scene>
        <scenesize width="3" height="2"/>
        <predefined>
            <object angle="0.000" X="1.275" type="Hammer" Y="1.410" width="0.450" height="0.180"/>
        </predefined>
        <background>
            <gradientstop pos="0.00">0.80;0.80;1.00;1.00</gradientstop>
            <gradientstop pos="1.00">0.50;0.50;0.90;1.00</gradientstop>
        </background>
    </scene>
    <goals/>
    <hints/>
</tbe-level>
```

Note: If you remove the `height` and `width` attributes from the hammer object and try again, TBE loads the level flawlessly. o_O

Revision: 2207f1bd8cc5af7e7b426fa828cf36931934f2a7

**Comment by kaa-ching** [comment]
Thanks for diagnosing the cause of the crash. I had seen it, but wasn't in the mood to figure it out yet.
Also thanks for providing me with a simple example.
